resources:
  - name: richmond
    type: git
    source:
      uri: https://github.com/seattle-beach/richmond
      branch: master

  - name: cf
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      organization: seattle-beach
      space: richmond

jobs:
- name: backend-build
  plan:
  - get: richmond
    trigger: true
    passed:
      - backend-test
  - task: backend-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: microsoft/dotnet
      inputs:
        - name: richmond
      outputs:
        - name: backend-publish
      run:
        path: richmond/backend/build.sh
        args:
          - richmond/backend/src
          - backend-publish
  - put: cf
    params:
      manifest: richmond/backend/manifest.yml
      path: backend-publish
      app: api
- name: backend-test
  plan:
  - get: richmond
    trigger: true
  - task: backend-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: microsoft/dotnet
      inputs:
        - name: richmond
      run:
        path: richmond/backend/test.sh
        args:
          - richmond/backend
- name: frontend-test
  plan:
  - get: richmond
    trigger: true
  - task: frontend-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: wernight/phantomjs
      inputs:
        - name: richmond
      run:
        path: phantomjs
        args:
          - richmond/frontend/jasmine/spec/run-jasmine.js
          - richmond/frontend/jasmine/SpecRunner.html
  - put: cf
    params:
      manifest: richmond/frontend/manifest.yml
